### ISSUE TITLE
[Bug]: Include statement in already included file does not work.

### ISSUE THREAD

**Issue by jahangirhussain** [stepci/stepci#141]
### What happened?

I have main file named master.yml. In include statement I am including file.yml. it is working fine when i write tests stright away in it. but it does not work if I include other file in file1.yml i.e include: ./file2.yml.

master.yml is: 

version: '1.1'
name: Rest API 
env:
  host: localhost:3000
include:
   - ./file1.yml

file1.yml is 
include: 
   - ./file2.yml

### What did you expect to happen?

Run tests as they were running in 1st order including scrnario.

### Version

2.6.6

### Environment

Node version 18.17.0

### Relevant log output

```shell
LaunchGood\rebuild\node_modules\@stepci\runner\dist\index.js:98
            co2: testResults.map(test => test.co2).reduce((a, b) => a + b),
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
Recursive includes don't work. We should probably deprecate the feature until we have a more robust solution

**Comment by sebastianwis** [comment]
Hi @jahangirhussain 
Thank you for your contribution here! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.

**Comment by mishushakov** [comment]
Since runner version 1.10.11, we don't have "include" anymore, you should instead JSON Refs (or reusables as we call them) instead
