### ISSUE TITLE
[Bug]: `--env` CLI flag parses value with `=` in them incorrectly

### ISSUE THREAD

**Issue by plungingChode** [stepci/stepci#151]
### What happened?

I tried to pass an environment variable with a value similar to `A=B`.
```
stepci --env 'env=A=B`
```
The variable was parsed as 
```js
{ env: "A" }
```

### What did you expect to happen?

It should have been parsed as
```js
{ env: "A=B" }
```

### Version

2.6.8

### Environment

Node v16.20.0

### How can we reproduce this bug?

Run `stepci --env 'env=A=B'`

### Would you be interested in working on a bugfix for this issue?

- [X] Yes! Assign me

**Comment by mishushakov** [comment]
Have you tried the below:

```sh
stepci -e 'A=B`
```

**Comment by sebastianwis** [comment]
Hey @plungingChode 
Thanks for creating the issue! Would you mind joining our Discord?
https://discord.com/invite/KqJJzJ3BTu

Would love to hear from you!

**Comment by plungingChode** [comment]
> Have you tried the below:
> 
> ```shell
> stepci -e 'A=B`
> 

Hi! Yes, but my issue is that if an environment variable passed as a CLI argument contains an equals sign (for some reason), anything after the second `=` is completely ignored. What I'd expect is for 
```
stepci -e 'var=A=B'
```
to be available to use in the workflow as `${{env.var}}`, having the value `A=B`. Instead, it is just parsed as `A`. If this is intended, please feel free to close the issue.
