### ISSUE TITLE
[Bug]: stepci doesn't respect system trusted root certificate authorities

### ISSUE THREAD

**Issue by bianchidotdev** [stepci/stepci#155]
### What happened?

I run caddy with a self-signed certificate for local development. This cert is installed in the system's trusted root CAs so that browsers and other programs can know to trust the Certificate Authority.

When running with stepci against my local app, I get the following error:
```
unable to get local issuer certificate
```

As far as I can tell, it's because stepci isn't using the system list of trusted CAs. 

It's possible I'm completely missing the mark on why I'm getting this error though.

### What did you expect to happen?

I expected either a) the system CA store to be used OR for there to be some option to specify a certificate to trust.

### Version

2.6.8

### Environment

Installed via brew (node 20.8.0)

### How can we reproduce this bug?

Follow [Caddy's local HTTPS docs](https://caddyserver.com/docs/automatic-https#local-https) to set up a local reverse proxy with a self-signed certificate.
Essentially:
```
# Caddyfile
local.bubbli.org {
	tls internal
	reverse_proxy "/*" localhost:5173
	reverse_proxy "/api/*" localhost:4000
}
```

Then run the following:
```
caddy trust
caddy run
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by bianchidotdev** [comment]
I'm further confused because I just set up a simple `got` request locally and it works with my setup. So, maybe it's something else in the ssl checking. I'll keep looking a little bit.

**Comment by bianchidotdev** [comment]
Yeah, I feel like it's something with trying to parse the certificate with `node:tls` but this is beyond my area of expertise. Note: this error occurs even if I try setting ssl to false in the check section.

I'm happy switching to testing the raw ports of my servers, but typically I like running everything through a production-like setup to test as similarly to prod as possible.

**Comment by mishushakov** [comment]
Have you tried setting `config.http.rejectUnauthorized` to false?

Eg.

```yaml
config:
  http:
    rejectUnauthorized: false
```

**Comment by bianchidotdev** [comment]
Finally got around to trying this. This does get me around the issue, so thank you. I thought I had looked at all the docs for ssl related config but I guess I missed that. This probably isn't an issue for anyone else since it seems to just be a self-signed certs issue, so I'm happy to close this out, especially now that it's a little more documented.

Thanks!

**Comment by mishushakov** [comment]
We should probably make the option default to true, as it has led some to confusion on the past

**Comment by bianchidotdev** [comment]
I'd agree with that. Especially given the http ssl valid check's existence. I initially tried setting `ssl: valid: false`, but it seemed like it wasn't even getting to the check phase.

**Comment by mishushakov** [comment]
Fixed in the latest version of the runner

**Comment by sebastianwis** [comment]
Hey @bianchidotdev 
Thank you for your contribution here! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.
