### ISSUE TITLE
Repeat steps until condition is met

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#169]

**Comment by BapAtRb** [comment]
Hey @mishushakov 😊
Is there a chance this feature is somewhere on the landscape? That would greatly help in some tests of mine, but unfortunately I cannot contribute myself as I am far from being programmer 😬
Thanks a lot!

**Comment by mishushakov** [comment]
This should already be working.



See: https://docs.stepci.com/guides/testing-http.html#conditions

and: https://docs.stepci.com/guides/retry-timeout.html

**Comment by BapAtRb** [comment]
That's right, I have tried the `retries` config, where my checks have condition on element in response body. I am not sure if the retry should ignore that check and focus only on status code but in my case no retry is attempted and failure thrown right away once condition is not met. I will appreciate any further advice here 🙏

**Comment by mishushakov** [comment]
The version supporting retries is yet not available on NPM. I'll let you know here when it happens

**Comment by BapAtRb** [comment]
Thank you a lot! Step CI seems to be a tool that perfectly matches all my requirements in terms of testing, hence I am truly looking forward to that release! 😊

P.S. Would it be possible for you to unveil the mystery of approximate time for when the release is planned? It will let me to plan other activities around it 😉

**Comment by mishushakov** [comment]
Published (v2.8.0)
