### ISSUE TITLE
[Bug]: Github Actions overrides workdir

### ISSUE THREAD

**Issue by mschfh** [stepci/stepci#187]
### What happened?

Github Actions passes `--workdir /github/workspace` to `docker run`, therefore overriding the `WORKDIR` defined in the Dockerfile and the action fails.

### What did you expect to happen?

The action completes.

### Version

action 2.7.2

### Environment

Github Actions

### Relevant log output

```shell
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/github/workspace/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
Fixed in the latest commit
