### ISSUE TITLE
[Bug]: Resolving local file references does not work

### ISSUE THREAD

**Issue by JFReuter-Fin** [stepci/stepci#191]
### What happened?

I cannot get local file references (`$ref: ./file.yaml`) to work. 

I can reproduce the problem using the `structure.yml` example from here: https://github.com/stepci/stepci/blob/main/examples/structure.yml

`stepci run ./structure.yml` fails to resolve `status.yml` and exits. It appears as if it tries to resolve the file from the node_modules folder of stepci, which obviously fails.

Please see the attached log output for details.

I will gladly assist in debugging this if necessary.

### What did you expect to happen?

stepci should properly resolve references to local files. It should look for files relative to the workflow yaml file.

### Version

2.7.2

### Environment

Node.js v21.2.0, Windows 11, Powershell 7.3.9

### How can we reproduce this bug?

1. Download both [structure.yml](raw.githubusercontent.com/stepci/stepci/main/examples/structure.yml) and [status.yml](https://raw.githubusercontent.com/stepci/stepci/main/examples/status.yml).
2. `stepci run structure.yml`

### Relevant log output

```shell
C:\dev\src\step> stepci run ./structure.yml

ⓘ  Anonymous usage data collected. Learn more on https://step.ci/privacy

(node:22024) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\felix.reuter\AppData\Roaming\npm\node_modules\stepci\node_modules\@stepci\runner\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\file.js:59
            throw new errors_js_1.ResolverError((0, ono_1.ono)(err, `Error opening file "${path}"`), path);
                  ^

ResolverError: Error opening file "C:\Users\felix.reuter\AppData\Roaming\npm\node_modules\stepci\node_modules\@stepci\runner\node_modules\@apidevtools\json-schema-ref-parser\status.yml\tests\example" 
ENOENT: no such file or directory, open 'C:\Users\felix.reuter\AppData\Roaming\npm\node_modules\stepci\node_modules\@stepci\runner\node_modules\@apidevtools\json-schema-ref-parser\status.yml\tests\example'
    at Object.read (C:\Users\felix.reuter\AppData\Roaming\npm\node_modules\stepci\node_modules\@stepci\runner\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\file.js:59:19) {
  code: 'ERESOLVER',
  source: 'C:\\Users\\felix.reuter\\AppData\\Roaming\\npm\\node_modules\\stepci\\node_modules\\@stepci\\runner\\node_modules\\@apidevtools\\json-schema-ref-parser\\status.yml\\tests\\example',
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ENOENT',
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}

Node.js v21.2.0
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
We're using a library called [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser) and I believe it has an issue when using windows (https://github.com/APIDevTools/json-schema-ref-parser/issues/303)

**Comment by mishushakov** [comment]
I have updated the runner version (1.12.0). Feel free to reopen if the issue still persists
