### ISSUE TITLE
(Docs) Improve README

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#2]
Users who did not visit the website, should be able to see the examples and features

**Comment by umeshchavda05** [comment]
@mishushakov can i work on this for hacktoberfest?

**Comment by mishushakov** [comment]
I'll reopen if we need any new changes in the example section again!

**Comment by sebastianwis** [comment]
Hi Umseh @umeshchavda05 
Thank you for your contribution here! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.
