### ISSUE TITLE
[Bug]: navbar toggle bar style bug

### ISSUE THREAD

**Issue by amitsaini144** [stepci/stepci#207]
### What happened?

on the home page, the black background is not toggling  on  "Get Started",  "Features" and "Pricing"

### What did you expect to happen?

the black background should toggle on each navbar item

### Version

2.8.0

### Environment

Node v18.16.0

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
I've noticed it too, not very important to fix

**Comment by amitsaini144** [comment]
Ok thankyou for the reply

**Comment by mishushakov** [comment]
Thanks for reporting anyways!
