### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#21]
When no arguments are specified we want to output the help screen

This could be accomplished by default command option in `yargs`
https://github.com/yargs/yargs/blob/main/docs/advanced.md#default-commands

**Comment by Dinoosawruss** [comment]
Happy to take a look at this as discussed in #8

**Comment by relby** [comment]
This also could be easily accomplished with [.demandCommand](https://yargs.js.org/docs/#api-reference-demandcommandmin1-minmsg) method.
I'd like to create a pull request on this issue.
