### ISSUE TITLE
[Bug]: Matchers for size and bodySize does not work correctly 

### ISSUE THREAD

**Issue by kucherenko** [stepci/stepci#218]
### What happened?

I tried to check that body size was geather than zero and got error when I used matches gte or ge.

### What did you expect to happen?

![screenshot-stepci com-2024 05 04-18_13_35](https://github.com/stepci/stepci/assets/159307/d91971dc-6fb2-40f4-a6a1-7372ffa1ebed)
![screenshot-stepci com-2024 05 04-18_14_51](https://github.com/stepci/stepci/assets/159307/b4965dc4-e87d-447a-9e99-9b11c869688a)
![screenshot-stepci com-2024 05 04-18_14_24](https://github.com/stepci/stepci/assets/159307/31992bf3-94e8-43b5-bdfa-723c7a7d2eff)
![screenshot-stepci com-2024 05 04-18_13_58](https://github.com/stepci/stepci/assets/159307/e08170ba-8c61-41bb-a74d-b30e2bff07b5)

### Version

on site

### Environment

on site

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
The playground is now updated. Feel free to reopen, if you're still experiencing the issue
