### ISSUE TITLE
Formula for Homebrew

### ISSUE THREAD

**Issue by muffl0n** [stepci/stepci#24]
It would be awesome to have a formula for [Homebrew](https://brew.sh/).

**Comment by mishushakov** [comment]
I'm a Mac user myself and would love this, but I don't know how to add formulas to Homebrew
Would you be able to help us out? We're good at accepting Pull Requests 😄

**Comment by muffl0n** [comment]
Gave it a try (with the help of https://github.com/zmwangx/homebrew-npm-noob): https://github.com/Homebrew/homebrew-core/pull/113109

**Comment by mishushakov** [comment]
Amazing, thanks! I'll monitor the PR and add brew as installation option once they merge!

**Comment by muffl0n** [comment]
They are asking for a test case. Could you help me out with that? I'm not confident enough with stepci to know what would be appropriate.

**Comment by mishushakov** [comment]
Sure! What I understand is we need to run some test to verify the software runs as expected
We could create a temporary test file, run it using the cli and verify the outputs

If this doesn't work within a brew script, I'll implement this as a test command on the CLI

**Comment by muffl0n** [comment]
Thanks for helping out!

**Comment by mishushakov** [comment]
Hello, @muffl0n
Any progress you can share with the community? Do you need any input from me to get this going?

Let me know 😉

**Comment by muffl0n** [comment]
I still didn't find the time to learn how to write a test for the formula. So if you have an idea how to do that, let me know! :)

**Comment by mishushakov** [comment]
Ok, thanks for update! I don't have time to get into that right now, but I will let you know if I have something 😉

**Comment by chenrui333** [comment]
This issue can be closed now.

```
$ brew install stepci
==> Fetching stepci
==> Downloading https://ghcr.io/v2/homebrew/core/stepci/manifests/2.6.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/stepci/blobs/sha256:1e41ea796ca2e6cae06d78d88a3c164906c7c0a64249
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:1e41ea796ca2e6cae06d78d88a3c
######################################################################## 100.0%
==> Pouring stepci--2.6.0.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/stepci/2.6.0: 9,296 files, 37.5MB
```

**Comment by muffl0n** [comment]
Thank you!
