### ISSUE TITLE
Add a bug report template

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#4]

**Comment by dejmedus** [comment]
I can work on this

**Comment by mishushakov** [comment]
@dejmedus you're welcome!

**Comment by sebastianwis** [comment]
Hi Julia @dejmedus 
Thank you for your contribution here! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.
