### ISSUE TITLE
(Docs) Add examples for working with files

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#42]

**Comment by hi-vishal** [comment]
can you assign this to me?

**Comment by mishushakov** [comment]
Hey, feel free to open a pull request!

**Comment by sebastianwis** [comment]
Hi @hi-vishal 
Thank you for your contribution! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.
