### ISSUE TITLE
(Docs) CLI Reference

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#8]
We want a doc, with all our CLI commands and options
You can already retrieve the list from the CLI by running `stepci --help`

**Comment by Dinoosawruss** [comment]
Hey happy to work on this if still required?

**Comment by mishushakov** [comment]
@Dinoosawruss Absolutely and you're welcome to contribute! Feel free to put it under `docs/cli-reference.md` and list it on `docs/README.md`.

Waiting happily for your Pull Request 😄

**Comment by mishushakov** [comment]
By the way, if you don't know how one could look like, here are some examples: [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference), [Prisma CLI](https://www.prisma.io/docs/reference/api-reference/command-reference), [Stripe CLI](https://stripe.com/docs/cli)

**Comment by Dinoosawruss** [comment]
Looks like I only get 2 args from `stepci --help`

```
> stepci --help
index.js [command]

Commands:
  index.js run [workflow]  run workflow

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]```

**Comment by Dinoosawruss** [comment]
```
index.js [command]

Commands:
  index.js run [workflow]  run workflow

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```
Just checking if these are all the arguments that need documenting?

**Comment by mishushakov** [comment]
Currently yes, but we'll still need that document, because we know people would search for it!

**Comment by Dinoosawruss** [comment]
Ok cool!

**Comment by mishushakov** [comment]
Also one more thing you could work on, related to this is a default command, when no arguments are specified
More details: https://github.com/stepci/stepci/issues/21

**Comment by mishushakov** [comment]
This issue is now resolved, we'll reopen it if we need to make any new changes to the CLI reference
