### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by smaktacular** [stepci/stepci#83]
### Would you be sad if Step CI did not exist?

7

### How likely would you recommend Step CI to a colleague?

10

### Is there something you dont like about Step CI?

Reusability is not going far enough atm. Enabling the user to write test in a DRYer way is something I'd love to see.
More examples, even if overlapping in one or the other point would help.
Templating is not working in all places, e.g. use an env value in another env value is a very common use  

### Do you have any ideas that could improve Step CI?

see things I don't like.
A VsCode extension similar to httpyac.

### Anything else you want to tell us?

I love the format of the tests, but even more the idea of being capable to use the workflows as a library and as a loadtesting tool. That alone is enough to make step ci look more attractive than JMeter. 

Happy Holidays! StepCI is a very good product already, keep it going!!!

**Comment by mishushakov** [comment]
Thank you so much for the feedback! We will take it into consideration
Feel free to add anything if you have new feedback

Happy holidays to you as well 😄
